### PR TITLE
Multipop

### PR DESCRIPTION
**Pull request by philipbg**
Changed "MegaPop" to "MultiPop" as mentioned here: https://github.com/gaynorr/AlphaSimR/issues/120#issuecomment-1609886575

### CODE REVIEW

**Comment by gregorgorjanc** [comment]
@philipbg @gaynorr looks ok - most changes are whitespace

@philipbg it would be good to mention this name change in the NEWS (or equivalent) file - I don't think anyone/many use this option at this stage, but good to document the change.

**Comment by philipbg** [comment]
@gregorgorjanc I am not sure why so much whitespace changes came about. I didn't hit space or enter. I just did find and replace.

**Comment by gregorgorjanc** [comment]
@philipbg whitespace changes likely came from RStudio defaults. I have the same settings;)

@philipbg NEWS file can be updated as we go along so that on the release you have it mostly done;)

**Comment by philipbg** [comment]
@gregorgorjanc it must be a default for emacs/magit too then

**Comment by gaynorr** [comment]
@philipbg The initial checks failed due to the Namespace file not reflecting the changes you made. I fixed this by deleting the Namespace file and reran `roxygen2::roxygenize()` to auto generate it again. 

I typically run "clean and install" in the "build" tab of RStudio before submitting a branch. This should update the documentation and Namespace file. It also serves as a check that everything is working by running running the unit tests and examples. Note that I have the "Generate documentation with Roxygen" box ticked in the "Configure build tools" menu. 

I do find that sometimes the Namespace and documentation doesn't get updated like it should. This usually results an error when running "Build". I suspect this issue comes from working on different computers with different RStudio options, but I haven't isolated the exact cause. The delete the Namespace file trick I used above usually resolves this.

**Pull request merged**
