### PR TITLE
Fixing #37 and partially also #38

### PR DESCRIPTION
**Pull request by gregorgorjanc**
These changes should address #37 as well as partially #38. I show below that they now output the appropriate pedigree (I have not checked recombinations though!), but I would appreciate code check to be on the safe side @gaynorr 

```
library(AlphaSimR)
founderGenomes <- quickHaplo(nInd = 3, nChr = 1, segSites = 100)
SP <- SimParam$new(founderGenomes)
SP$setTrackPed(TRUE)
basePop <- newPop(founderGenomes)
x1 <- reduceGenome(basePop[1], nProgeny = 10)
basePop[1]@id
# [1] "1"
basePop[1]@father
# [1] "0"
basePop[1]@mother
# [1] "0"
x1@iid
# [1]  4  5  6  7  8  9 10 11 12 13
x1@id
# [1] "4"  "5"  "6"  "7"  "8"  "9"  "10" "11" "12" "13"
x1@mother
# [1] "0" "0" "0" "0" "0" "0" "0" "0" "0" "0"
x1@father
# [1] "0" "0" "0" "0" "0" "0" "0" "0" "0" "0"
x1@ploidy
# [1] 1
SP$pedigree
# mother father isDH
# 1       0      0    0
# 2       0      0    0
# 3       0      0    0
# 4       0      0    0
# 5       0      0    0
# 6       0      0    0
# 7       0      0    0
# 8       0      0    0
# 9       0      0    0
# 10      0      0    0
# 11      0      0    0
# 12      0      0    0
# 13      0      0    0

pop = randCross(basePop, nCrosses = 3, nProgeny = 2)
pop@iid
# [1]  14 15 16 17 18 19
pop@id
# [1] "14" "15" "16" "17" "18" "19"
pop@mother
# [1] "1" "1" "1" "1" "2" "2"
pop@father
# [1] "2" "2" "3" "3" "3" "3"
pop@ploidy
# [1] 2
SP$pedigree
# mother father isDH
# ...
# 14      1      2    0
# 15      1      2    0
# 16      1      3    0
# 17      1      3    0
# 18      2      3    0
# 19      2      3    0

x2 <- reduceGenome(pop[1], nProgeny = 5)
pop[1]@id
# [1] "14"
pop[1]@father
# [1] "2"
pop[1]@mother
# [1] "1"
x2@iid
# [1]  20 21 22 23 24
x2@id
# [1] "20" "21" "22" "23" "24"
x2@mother
# [1] "1" "1" "1" "1" "1"
x2@father
# [1] "2" "2" "2" "2" "2"
x2@ploidy
# [1] 1
SP$pedigree
# mother father isDH
# ...
# 20      1      2    0
# 21      1      2    0
# 22      1      2    0
# 23      1      2    0
# 24      1      2    0

x3 <- reduceGenome(pop[1], nProgeny = 5, keepParents = FALSE)
pop[1]@id
# [1] "14"
pop[1]@father
# [1] "2"
pop[1]@mother
# [1] "1"
x3@iid
# [1] 25 26 27 28 29
x3@id
# [1] "25" "26" "27" "28" "29"
x3@mother
# [1] "14" "14" "14" "14" "14"
x3@father
# [1] "14" "14" "14" "14" "14"
x3@ploidy
# [1] 1
SP$pedigree
# ...
# 25     14     14    0
# 26     14     14    0
# 27     14     14    0
# 28     14     14    0
# 29     14     14    0

y1 <- mergeGenome(x1, x1, crossPlan = cbind(x1@id, x1@id))
x1@id
# "4"  "5"  "6"  "7"  "8"  "9"  "10" "11" "12" "13"
y1@id
# [1] "30" "31" "32" "33" "34" "35" "36" "37" "38" "39"
y1@mother
# [1]  "4"  "5"  "6"  "7"  "8"  "9"  "10" "11" "12" "13"
y1@father
# [1] "4"  "5"  "6"  "7"  "8"  "9"  "10" "11" "12" "13"
y1@ploidy
# [1] 2
SP$pedigree
# ...
# 30      4      4    0
# 31      5      5    0
# 32      6      6    0
# 33      7      7    0
# 34      8      8    0
# 35      9      9    0
# 36     10     10    0
# 37     11     11    0
# 38     12     12    0
# 39     13     13    0

y2 <- mergeGenome(x2, x2, crossPlan = cbind(x2@id, x2@id))
x2@id
# "20" "21" "22" "23" "24"
y2@id
# [1] "40" "41" "42" "43" "44"
y2@mother
# [1]  "20" "21" "22" "23" "24"
y2@father
# [1] "20" "21" "22" "23" "24"
y2@ploidy
# [1] 2
SP$pedigree
# ...
# 40     20     20    0
# 41     21     21    0
# 42     22     22    0
# 43     23     23    0
# 44     24     24    0

y3 <- mergeGenome(x3, x3, crossPlan = cbind(x3@id, x3@id))
x3@id
# "25" "26" "27" "28" "29"
y3@id
# [1] "45" "46" "47" "48" "49"
y3@mother
# [1]  "25" "26" "27" "28" "29"
y3@father
# [1] "25" "26" "27" "28" "29"
y3@ploidy
# [1] 2
SP$pedigree
# ...
# 45     25     25    0
# 46     26     26    0
# 47     27     27    0
# 48     28     28    0
# 49     29     29    0
```

### CODE REVIEW

**Comment by gaynorr** [comment]
It doesn't look like these changes will work. Specifically, it doesn't work with the way I've started handling id and iid (id just provides flavor and iid is a critical value for tracking recombination). 

I'm working these changes separately and I just pushed my most recent work to the devel branch. I haven't had a chance to test them yet, so feel free to give them a whirl if you have time. Otherwise, I plan to test them and finish up sometime tomorrow.

FYI: I'm also working on a number of new features in this branch that you'll see noted in the NEWS file. Several of them are commented out at the moment.

**Comment by gregorgorjanc** [comment]
I have seen other stuff - great!!!

I think I now understand better how you handle ID (have left a question just to understand this - I need to since we need to make a dedicated `beeCross()` - current functionality does not give us all the behaviour we need - more on that later).

I am not sure I follow recombination side of things - before you were using the `hist` generated in the C++ code, but now you don't seem to pass that onwards? https://github.com/gaynorr/AlphaSimR/commit/2ede5d1f6207f80ac44fdbaaccf474baee599b99

**Comment by gaynorr** [comment]
The recombination history is getting pushed along to the newPop function which is responsible for adding it to SimParam. I am relying on C++ code to generate that reduceGenome, because it involves the simulation of meiosis (map distance is set to zero when you don't want meiosis). I am generating it in R code for doubleGenome and reduceGenome, because there is no simulation of meiosis. 

I am only passing which chromosomes get passed along in the last two functions, because the pullIbdHaplo function will handle the recursive lookup. I still need to check this function to make sure it handles all the ploidy changes. It will have to guess which chromosomes come from the male and female based on each individual's ploidy. I don't think all the rules are currently in place.

The newPop function is also updating the pedigree. I'm treating every new genotype as a separate entry in the pedigree. I know this doesn't match the desired state for bees. For bees, you could potentially pass the isDH flag to indicate drones. This flag currently doesn't do anything. It is just present for potential future development of a pedigree relationship matrix.

I should probably write a separate version of newPop, because the current one is getting used in two different ways. The first is by the user when converting a MapPop to a Pop. The second is being used by AlphaSimR functions to create a Pop from a RawPop. There are a lot of additional arguments for the internal use that are being hidden from the user using the ... argument. I did this to avoid showing the user too many confusing arguments. In hind sight, it would be better to just have separate function that isn't exported.

**Comment by gregorgorjanc** [comment]
I agree that having arguments "hidden" is not great and that you don't want to overburden users with stuff they don't need.

**Pull request closed without merging**
